/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yael.proyectofinalcurso;

import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author asm_1
 */
public class Contactos extends javax.swing.JFrame {
    private ManejadorUsuarios mu;
    private ManejadorContactos mc;
    private int posicion_contacto_seleccionado = -1;
    private boolean nuevo_contacto = false;
    /**
     * Creates new form Contactos
     */
    public Contactos() {
        initComponents();
        int height = Toolkit.getDefaultToolkit().getScreenSize().height;
        int width = Toolkit.getDefaultToolkit().getScreenSize().width;
        
        height -= this.getSize().height;
        width -= this.getSize().width;
        
        this.setLocation(width/2, height /2);
        
        this.jMenuBar.setVisible(false);
        this.jSplitPaneAgenda.setVisible(false);
        
        this.mu = new ManejadorUsuarios();
        
        this.jButtonEditar.setVisible(false);
        this.jButtonEliminar.setVisible(false);
        this.jButtonCancelar.setVisible(false);
        this.jButtonGuardar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneAgenda = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListContactos = new javax.swing.JList<>();
        jPanelContacto = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelCumpleanos = new javax.swing.JLabel();
        jTFNombreContacto = new javax.swing.JTextField();
        jTFTelefonoContacto = new javax.swing.JTextField();
        jTFCorreoContacto = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jFTFCumpleanosContacto = new javax.swing.JFormattedTextField();
        jButtonEditar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelLogin = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jPFPassword = new javax.swing.JPasswordField();
        jButtonIniciarSesion = new javax.swing.JButton();
        jButtonCrearUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuContactos = new javax.swing.JMenu();
        jMenuItemAgregarContacto = new javax.swing.JMenuItem();
        jMenuItemEditarContacto = new javax.swing.JMenuItem();
        jMenuItemEliminarContacto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");

        jSplitPaneAgenda.setDividerLocation(200);

        jListContactos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jListContactos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListContactos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListContactosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListContactos);

        jSplitPaneAgenda.setLeftComponent(jScrollPane1);

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNombre.setLabelFor(jTFNombreContacto);
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setRequestFocusEnabled(false);

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelTelefono.setLabelFor(jTFTelefonoContacto);
        jLabelTelefono.setText("Número de teléfono:");
        jLabelTelefono.setRequestFocusEnabled(false);

        jLabelCorreo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelCorreo.setLabelFor(jTFCorreoContacto);
        jLabelCorreo.setText("Correo electrónico:");
        jLabelCorreo.setRequestFocusEnabled(false);

        jLabelCumpleanos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelCumpleanos.setLabelFor(jFTFCumpleanosContacto);
        jLabelCumpleanos.setText("Fecha de nacimiento:");
        jLabelCumpleanos.setRequestFocusEnabled(false);

        jTFNombreContacto.setEditable(false);
        jTFNombreContacto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jTFTelefonoContacto.setEditable(false);
        jTFTelefonoContacto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jTFCorreoContacto.setEditable(false);
        jTFCorreoContacto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jFTFCumpleanosContacto.setEditable(false);
        jFTFCumpleanosContacto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFTFCumpleanosContacto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContactoLayout = new javax.swing.GroupLayout(jPanelContacto);
        jPanelContacto.setLayout(jPanelContactoLayout);
        jPanelContactoLayout.setHorizontalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContactoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCorreo)
                            .addComponent(jLabelCumpleanos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNombreContacto)
                            .addComponent(jTFCorreoContacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                            .addComponent(jTFTelefonoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                            .addComponent(jFTFCumpleanosContacto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContactoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContactoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar)))
                .addContainerGap())
        );
        jPanelContactoLayout.setVerticalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonEditar))
                .addGap(5, 5, 5)
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addGap(18, 18, 18)
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCorreoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCumpleanos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFCumpleanosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPaneAgenda.setRightComponent(jPanelContacto);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabelUsuario.setText("Usuario:");

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabelPassword.setText("Contraseña:");

        jTFUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPFPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonIniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonIniciarSesion.setText("Iniciar sesión");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        jButtonCrearUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCrearUsuario.setText("Crear usuario");
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vivaldi", 2, 48)); // NOI18N
        jLabel1.setText("Bienvenido a tu agenda personal");

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPassword)
                                    .addComponent(jLabelUsuario))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(128, 128, 128)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearUsuario)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jMenuFile.setText("File");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSalir);

        jMenuBar.add(jMenuFile);

        jMenuContactos.setText("Contactos");

        jMenuItemAgregarContacto.setText("Nuevo Contacto");
        jMenuItemAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarContactoActionPerformed(evt);
            }
        });
        jMenuContactos.add(jMenuItemAgregarContacto);

        jMenuItemEditarContacto.setText("Editar Contacto");
        jMenuItemEditarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarContactoActionPerformed(evt);
            }
        });
        jMenuContactos.add(jMenuItemEditarContacto);

        jMenuItemEliminarContacto.setText("Eliminar contacto");
        jMenuItemEliminarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarContactoActionPerformed(evt);
            }
        });
        jMenuContactos.add(jMenuItemEliminarContacto);

        jMenuBar.add(jMenuContactos);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPaneAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarContactoActionPerformed
        this.nuevo_contacto = true;
        
        this.prepararIngresoDatos();
    }//GEN-LAST:event_jMenuItemAgregarContactoActionPerformed

    private void jMenuItemEditarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarContactoActionPerformed
        if (this.posicion_contacto_seleccionado > -1)
            this.prepararIngresoDatos();
        else{
            JOptionPane.showMessageDialog(this, "No has seleccionado ningun contacto", "¡Espera!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemEditarContactoActionPerformed

    private void jMenuItemEliminarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarContactoActionPerformed
        if (this.posicion_contacto_seleccionado > -1)
            this.clickEliminarBoton();
        else{
            JOptionPane.showMessageDialog(this, "No has seleccionado ningun contacto", "¡Espera!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemEliminarContactoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        this.clickGuardarBoton();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.clickCancelarBoton();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        this.clickEliminarBoton();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        this.prepararIngresoDatos();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jListContactosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListContactosValueChanged
        this.posicion_contacto_seleccionado = this.jListContactos.getSelectedIndex();
        if (this.posicion_contacto_seleccionado > -1)
            this.mostrarDatosContacto();
    }//GEN-LAST:event_jListContactosValueChanged

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        String file_name = this.mu.login(this.jTFUsuario.getText(), new String(this.jPFPassword.getPassword()));
        
        if (file_name != null) {
            this.mc = new ManejadorContactos(file_name);
            this.cargarListaNombresContactos();
            
            this.jPanelLogin.setVisible(false);
            this.jMenuBar.setVisible(true);
            this.jSplitPaneAgenda.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrectos, intentelo de nuevo.", "¡Atención!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed
        String usuario = "", password = "", confirmar_password_mensaje = "";
        boolean password_confirmado = false;
        do{
            usuario = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre de usuario", "Nuevo Usuario", JOptionPane.PLAIN_MESSAGE);
        } while (usuario != null && usuario.trim().equals(""));
        
        do{
            password = JOptionPane.showInputDialog(this, "Ingrese contraseña del usuario", "Nuevo Usuario", JOptionPane.PLAIN_MESSAGE);
        } while (password != null && password.trim().equals(""));
        
        confirmar_password_mensaje = "Confirme la contraseña del usuario.";
        do{
            confirmar_password_mensaje = JOptionPane.showInputDialog(this, confirmar_password_mensaje, "Nuevo Usuario", JOptionPane.PLAIN_MESSAGE);
            try{
                if(confirmar_password_mensaje.equals(password)){
                    password_confirmado = true;
                } else {
                    confirmar_password_mensaje = "Las contraseñas no coindicen.\nConfirme la contraseña del usuario.";
                }
            } catch (Exception e){}
            
        } while (!password_confirmado && confirmar_password_mensaje != null);
        
        if (usuario != null && password != null && password_confirmado){
            if (this.mu.agregarUsuario(usuario, password)) {
                JOptionPane.showMessageDialog(this, "Usuario creado con éxito, ahora ingrese por favor.", "¡Éxito!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Ese usuario ya existe, intente con otro nombre.", "¡Espera!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contactos().setVisible(true);
            }
        });
    }
    
    private void cargarListaNombresContactos() {
        this.jListContactos.setModel(mc.obtenerListaDeNombres());
    }
    
    private void prepararIngresoDatos() {
        this.jButtonEditar.setVisible(false);
        this.jButtonEliminar.setVisible(false);
        
        this.jButtonCancelar.setVisible(true);
        this.jButtonGuardar.setVisible(true);
        
        this.jTFNombreContacto.setEditable(true);
        this.jTFTelefonoContacto.setEditable(true);
        this.jTFCorreoContacto.setEditable(true);
        this.jFTFCumpleanosContacto.setEditable(true);
        
        if (this.nuevo_contacto){
            this.jTFNombreContacto.setText("");
            this.jTFTelefonoContacto.setText("");
            this.jTFCorreoContacto.setText("");
            this.jFTFCumpleanosContacto.setText("");
        }
        this.jListContactos.setEnabled(false);
    }
    
    private void clickGuardarBoton() {
        Contacto c = new Contacto();
            
        c.setNombre(this.jTFNombreContacto.getText());
        c.setNumero_telefonico(this.jTFTelefonoContacto.getText());
        c.setCorreo(this.jTFCorreoContacto.getText());
        c.setFecha_cumpleanos(this.jFTFCumpleanosContacto.getText());
        
        if (!c.getNombre().trim().equals("") && !c.getNumero_telefonico().trim().equals("")){
            if (this.nuevo_contacto){
                this.jTFNombreContacto.setText("");
                this.jTFTelefonoContacto.setText("");
                this.jTFCorreoContacto.setText("");
                this.jFTFCumpleanosContacto.setText("");
                
                this.mc.agregarContacto(c);
                this.nuevo_contacto = false;
            } else {
                this.mc.editarContacto(this.posicion_contacto_seleccionado, c);
            }
            this.cargarListaNombresContactos();

            this.jButtonCancelar.setVisible(false);
            this.jButtonGuardar.setVisible(false);

            this.jTFNombreContacto.setEditable(false);
            this.jTFTelefonoContacto.setEditable(false);
            this.jTFCorreoContacto.setEditable(false);
            this.jFTFCumpleanosContacto.setEditable(false);

            this.jListContactos.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debes ingresar NOMBRE y NÚMERO DE TELÉFONO para guardar el contacto", "¡Espera!", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void clickCancelarBoton() {
        this.jButtonCancelar.setVisible(false);
        this.jButtonGuardar.setVisible(false);
        
        this.jTFNombreContacto.setEditable(false);
        this.jTFTelefonoContacto.setEditable(false);
        this.jTFCorreoContacto.setEditable(false);
        this.jFTFCumpleanosContacto.setEditable(false);
        
        if (this.nuevo_contacto) {
            this.jTFNombreContacto.setText("");
            this.jTFTelefonoContacto.setText("");
            this.jTFCorreoContacto.setText("");
            this.jFTFCumpleanosContacto.setText("");
        } else {
            this.mostrarDatosContacto();
        }
    }
    
    private void clickEliminarBoton() {
        int resp = JOptionPane.showConfirmDialog(this, "¿Esta seguro de elimminar a " + this.jTFNombreContacto.getText() + "?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (resp == 0) {
            this.mc.eliminarContacto(this.posicion_contacto_seleccionado);
            this.cargarListaNombresContactos();
        }
    }
    
    private void mostrarDatosContacto() {
        this.jButtonEditar.setVisible(true);
        this.jButtonEliminar.setVisible(true);
        
        Contacto c = this.mc.getContacto(this.posicion_contacto_seleccionado);
        
        this.jTFNombreContacto.setText(c.getNombre());
        this.jTFTelefonoContacto.setText(c.getNumero_telefonico());
        this.jTFCorreoContacto.setText(c.getCorreo());
        this.jFTFCumpleanosContacto.setText(c.getFecha_cumpleanos());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JFormattedTextField jFTFCumpleanosContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCumpleanos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JList<String> jListContactos;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuContactos;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAgregarContacto;
    private javax.swing.JMenuItem jMenuItemEditarContacto;
    private javax.swing.JMenuItem jMenuItemEliminarContacto;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPanelContacto;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPaneAgenda;
    private javax.swing.JTextField jTFCorreoContacto;
    private javax.swing.JTextField jTFNombreContacto;
    private javax.swing.JTextField jTFTelefonoContacto;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}